<?php

namespace PioCMS\Engine;

/**
 * Description of Language
 *
 * @author Adi
 */
class Language {

    public static $lang = 'pl';
    public static $array = array(
        'table_name' => 'Nazwa tabeli nie może być pusta',
        'website' => 'WirtualnyGaraz.pl',
        'model_not_exist' => 'Brak modelu "%s"',
        'router_not_exist' => 'Router "%s" nie istnieje',
        'homepage' => 'Strona główna',
        'homepage_h1' => 'Zarejestruj się już dziś <br>w <span class="add">Wirtualnym Garażu</span>',
        'first_name' => 'Imię',
        'mail' => 'Adres e-mail',
		'mail_not_exist' => 'W bazie taki adres e-mail nie istnieje',
        'password' => 'Hasło',
        'password_repeat' => 'Potwórz hasło',
		'password_was_send' => 'Nowe hasło zostało wysłane na podany adres e-mail',
		'password_new' => 'Prośba o wygenerowanie nowego hasła',
		'password_new_body' => 'Oto Twoje nowe hasło: {password}',
        'login' => 'Logowanie',
		'login_error' => 'Musisz się zalogować',
		'login_error_default' => 'Podane dane są nieprawidłowe',
        'logout' => 'Wyloguj',
        'button_login' => 'Zaloguj',
        'register' => 'Rejestracja',
        'button_register' => 'Załóż konto',
        'forgot_password' => 'Przypomnij hasło',
        'gallery' => 'Galeria',
		'gallery_drop' => 'Przeciągnij by dodać zdjęcia',
		'gallery_remove_photo' => 'Usuń zdjęcie',
        'my_account' => 'Przejdź do konta',
		'user_profile' => 'Profil',
        'app_about_header' => 'O aplikacji',
		'app_info' => '',
		'app_info_info1_label' => 'Historia napraw',
		'app_info_info1' => 'Możesz śledzić historię napraw swojego pojazdu.',
		'app_info_info2_label' => 'Wydatki',
		'app_info_info2' => 'Rozliczanie wydatków na samochód bywa koszmarne? Od dziś to już nie problem. Podasz liczbę kilometrów, litrów i cenę paliwa a system sam wyliczy resztę.',
		'app_info_info3_label' => 'Przypomnienia',
		'app_info_info3' => 'Zapominasz o wymiane oleju, przeglądzie lub ubezpieczeniu?<br />Podasz datę i treść przypomnienia, a tydzień wcześniej otrzymasz od nas wiadomość :)',
		'app_info_info4_label' => '',
		'app_info_info4' => '',
        'app_about_us' => 'Mówią o nas',
        'app_our_car' => 'Nasze samochody',
        'show_more' => 'Zobacz więcej',
        'vehicle_list' => 'Lista pojazdów',
		'vehicle_info' => 'Opis pojazdu %s',
		'vehicle_edit_form' => 'Formularz edycji pojazdu',
		'vehicle_button_edit' => 'Edytuj informacje', 
		'vehicle_button_remove' => 'Usuń pojazd',
        'view_not_exist' => 'Brak widoku "%s"',
		'error_404' => 'Strona o podanym adresie nie istnieje',
		'error_404_header' => 'Brak strony',
		'error' => 'Błąd',
		'user_panel' => 'Panel',
		'user_edit_profile' => 'Edytuj profil',
		'user_notify' => 'Przypomnienia',
		'button_add_vehicle' => 'Dodaj pojazd',
		'save_changes' => 'Zapisz zmiany',
		'save_was_changes' => 'Zmiany zostały zapisane',
		'button_edit' => 'Edytuj',
		'button_delete' => 'Usuń',
		'mark' => 'Marka',
		'model' => 'Model',
		'year' => 'Rok produkcji',
		'fuel' => 'Rodzaj paliwa',
		'transmission' => 'Skrzynia biegów',
		'colour' => 'Kolor',
		'doors' => 'Liczba drzwi',
		'car_type' => 'Rodzaj samochodu',
		'price' => 'Cena zakupu',
		'date_purchase' => 'Data zakupu',
		'engine' => 'Pojemność silnika',
		'power' => 'Moc silnika',
		'mileage' => 'Przebieg',
		'unit' => 'Jednostka',
		'refuel_list' => 'Lista tankowań',
		'refuel_list_last' => 'Lista ostatnich tankowań',
		'refuel_add' => 'Dodaj tankowanie',
		'refuel_add_success' => 'Dodano tankowanie',
		'price_per_galon' => 'Cena za litr',
		'total_galon' => 'Liczba litrów',
		'galons' => 'Litrów',
		'expenses' => 'Wydano',
		'total_price' => 'Cena całkowita',
		'mileage_per_tank'=>'Liczba kilometrów',
		'refuel_date'=> 'Data tankowania',	
		'repair_list' => 'Lista napraw',
		'repair_list_last' => 'Lista ostatnich napraw',
		'repair_add' => 'Dodaj naprawę',
		'repair_price' => 'Koszt naprawy',
		'repair_date' => 'Data naprawy',
		'repair_average' => 'Średnia',
		'repair_description' => 'Opis naprawy',
		'vehicle' => 'Pojazd',
		'vehicle_select' => 'Wybierz pojazd z listy',
		'vehicle_total_mileage' => 'przejechanych kilometrów',
		'vehicle_total_galon' => 'zatankowanych litrów',
		'vehicle_total_expenses' => 'wydanych PLN',
		'workshop' => 'Warsztat samochodowy',
		'currency_format' => '%s zł',
		'galon_format' => '%s l'
    );

    public static function trans($variable) {
        return isset(self::$array[$variable]) ? self::$array[$variable] : "";
    }

}
